### ISSUE TITLE
valohai-utils should ignore input defaults pointing to local paths when updating the yaml

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-utils#49]
If you have:
```
inputs = {
    "classes": ".data/classes.txt",
    "train": ".data/train/train.tfrecord",
    "test": ".data/test/test.tfrecord",
    "weights": ".data/weights/yolov3.tf.data-00000-of-00001",
}

valohai.prepare(step="train", default_inputs=inputs)
```

You now get:
```
    inputs:
    - name: classes
      default:
      - .data/classes.txt
      optional: false
    - name: train
      default:
      - .data/train/train.tfrecord
      optional: false
    - name: test
      default:
      - .data/test/test.tfrecord
      optional: false
    - name: weights
      default:
      - .data/weights/yolov3.tf.data-00000-of-00001
      optional: false
```

You should get:
```
    inputs:
    - name: classes
      optional: false
    - name: train
      optional: false
    - name: test
      optional: false
    - name: weights
      optional: false
```
