### ISSUE TITLE
Bool parameters are not parsed correctly from the CLI

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-utils#78]
With this code:
```
params = {
    'falseflag': True,
    'trueflag': False,
}

valohai.prepare(step='paramtest', default_parameters=params)

print(valohai.parameters('falseflag').value)
print(valohai.parameters('trueflag').value)
```

This YAML
```
    parameters:
    - name: falseflag
      default: false
      description: This is a flag parameter.
      multiple-separator: ','
      pass-false-as: --falseflag=false
      pass-true-as: --falseflag=true
      type: flag
    - name: trueflag
      default: true
      description: This is a flag parameter.
      multiple-separator: ','
      pass-false-as: --trueflag=false
      pass-true-as: --trueflag=true
      type: flag
```

And this CLI command:
```
python ./paramtest.py --falseflag=false --trueflag=true
```

We get this printout
```
True
True
```

The reason is that `valohai-utils` CLI parsing expects flags and not booleans. 

We should move to expecting the `pass-false-as` and `pass-true-as` bool-like behavior for the YAMLgen + parsing.
